-- Generated by ebean 11.27.1 at 2018-11-30T12:39:09.591020200Z
drop trigger general_descriptor_history_upd;
drop view general_descriptor_with_history;
alter table general_descriptor drop column sys_period_start;
alter table general_descriptor drop column sys_period_end;
drop table general_descriptor_history;

drop table if exists general_descriptor;
drop sequence if exists general_descriptor_seq;

