-- Generated by ebean 11.27.1 at 2018-11-30T12:39:09.591020200Z
create table general_descriptor (
  id                            bigint not null,
  type                          varchar(255),
  severity                      varchar(255),
  provider_http_location        varchar(255),
  json_path                     varchar(255),
  args_json_paths               array,
  request                       varchar(1000),
  optimistic_version            integer not null,
  constraint pk_general_descriptor primary key (id)
);
create sequence general_descriptor_seq;

alter table general_descriptor add column sys_period_start datetime(6) default now(6);
alter table general_descriptor add column sys_period_end datetime(6);
create table general_descriptor_history(
  id                            bigint,
  type                          varchar(255),
  severity                      varchar(255),
  provider_http_location        varchar(255),
  json_path                     varchar(255),
  args_json_paths               array,
  request                       varchar(1000),
  optimistic_version            integer,
  sys_period_start              datetime(6),
  sys_period_end                datetime(6)
);
create view general_descriptor_with_history as select * from general_descriptor union all select * from general_descriptor_history;

create trigger general_descriptor_history_upd before update,delete on general_descriptor for each row call "io.ebean.config.dbplatform.h2.H2HistoryTrigger";
